{
	"schema_version": "1.6.0",
	"id": "RHSA-2004:058",
	"modified": "2024-11-21T22:57:36Z",
	"published": "2024-09-15T14:25:00Z",
	"related": [
		"CVE-2003-0973",
		"CVE-2004-0096"
	],
	"summary": "Red Hat Security Advisory: mod_python security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::as",
				"name": "mod_python",
				"purl": "pkg:rpm/redhat/mod_python"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::as",
				"name": "mod_python-debuginfo",
				"purl": "pkg:rpm/redhat/mod_python-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::desktop",
				"name": "mod_python",
				"purl": "pkg:rpm/redhat/mod_python"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::desktop",
				"name": "mod_python-debuginfo",
				"purl": "pkg:rpm/redhat/mod_python-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::es",
				"name": "mod_python",
				"purl": "pkg:rpm/redhat/mod_python"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::es",
				"name": "mod_python-debuginfo",
				"purl": "pkg:rpm/redhat/mod_python-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::ws",
				"name": "mod_python",
				"purl": "pkg:rpm/redhat/mod_python"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:3::ws",
				"name": "mod_python-debuginfo",
				"purl": "pkg:rpm/redhat/mod_python-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.0.3-3.ent"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2004:058.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2004:058"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#low"
		},
		{
			"type": "ARTICLE",
			"url": "http://www.modpython.org/pipermail/mod_python/2003-November/014532.html"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2004/rhsa-2004_058.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2003-0973"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1617112"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2003-0973"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2003-0973"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2004-0096"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=430510"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2004-0096"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2004-0096"
		}
	]
}
