{
	"schema_version": "1.6.0",
	"id": "RHSA-2023:4282",
	"modified": "2024-09-13T18:51:30Z",
	"published": "2024-09-13T18:51:30Z",
	"related": [
		"CVE-2023-24329"
	],
	"summary": "Red Hat Security Advisory: Red Hat Virtualization Host 4.4.z SP 1 security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:rhev_hypervisor:4.4::el8",
				"name": "redhat-virtualization-host",
				"purl": "pkg:rpm/redhat/redhat-virtualization-host"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:4.5.3-202307191258_8.6"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:4282.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhev_hypervisor:4.4::el8",
				"name": "redhat-virtualization-host-image-update",
				"purl": "pkg:rpm/redhat/redhat-virtualization-host-image-update"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:4.5.3-202307191258_8.6"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:4282.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2023:4282"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#important"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2173917"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2212762"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2023/rhsa-2023_4282.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2023-24329"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2023-24329"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-24329"
		},
		{
			"type": "ARTICLE",
			"url": "https://pointernull.com/security/python-url-parse-problem.html"
		}
	]
}
